language: cpp
matrix:
  include:
  - os: linux
    sudo: enabled
    dist: xenial
  - os: osx
    osx_image: xcode6.4
env:
  matrix:
  - BUILD_FILENAME="build-$TRAVIS_OS_NAME.$TRAVIS_BUILD_NUMBER-$(date '+%Y-%m-%d_%H_%M_%S').tgz"
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then autobuild/synfigstudio-linux-build.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then autobuild/synfigstudio-osx-build.sh; fi
git:
  depth: 1
  submodules: false
