language: cpp

git:
  depth: 1
  submodules: false
  
env:
  global:
    - BUILD_FILENAME="build-$TRAVIS_OS_NAME.$TRAVIS_BUILD_NUMBER-$(date '+%Y-%m-%d_%H_%M_%S').tgz"
    - DEBUG=1
    - MAKE_THREADS=8

cache:
 - ccache
 
#test
 
matrix:
  include:
  
  - os: linux
    name: "Synfig Studio Ubuntu 16.04 (Xenial)"
    sudo: required
    dist: xenial
    script: autobuild/synfigstudio-linux-build.sh
        
  - os: osx
    name: "Synfig Studio OS X 10.10 (Yosemite)"
    sudo: required
    osx_image: xcode6.4
    script: sudo autobuild/synfigstudio-osx-build.sh
    
  allow_failures:
    - os: osx
    
after_failure:
  - cat $TRAVIS_BUILD_DIR/config.log
